### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by EmmaSweeney** [weijia-cheng/leo-tolstoy_the-power-of-darkness_louise-maude_aylmer-maude#1]
**Dramatis Personae:**

- [x] Each line is in sentence case. Characters like "Women, Girls, and People" should be lower cased.

- [x] We remove the last periods from each character description.

- The scene description can keep its period.

- [x] I think the title needs to be Dramatis Personae. There was [a conversation](https://groups.google.com/g/standardebooks/c/1FEVR_dgJns/m/CAUNoY1WCQAJ) about using Characters as a title, and Alex preferred Dramatis Personae. Also, 99% of the plays produced use Dramatis Personae as the title.

**All Acts:**

- [x] Characters mentioned in the introductory scene descriptions are also tagged with `<b epub:type="z3998:persona">`.

- [x] In your page scans, there are final stage directions ("Curtain.") that have margins like the introductory scene descriptions, separating them from the dialogue. This makes me think that these should be formatted as "high-level stage directions" and placed outside of the `<table>`s (see [SEMOS 7.6.7.3](https://standardebooks.org/manual/1.6.2/single-page#7.6.7.3) for  an example).

**Act 4:**

- [x] The table id should be `id="table-2"` since it is the second table in the file ([SEMOS 5.1.2.3](https://standardebooks.org/manual/1.6.2/single-page#5.1.2.3)).

-  Make sure to also change the value in the link.

- [x] I think there is a way to avoid using a `<div>`. You can surround everything from "Variation" to "Scene II" in a header like this:
```
				<header>
					<h3 epub:type="title">Variation</h3>
					<p>Instead of the <a href="#table-1">end of Act <span epub:type="z3998:roman">IV</span></a> the following variation may be read, and is the one usually acted.</p>
					<p>
						<span epub:type="label">Scene</span>
						<span epub:type="ordinal z3998:roman">II</span>
					</p>
				</header>
```

- [x] This would require the CSS to be changed to:

```
header > p:first-of-type{
	text-align: initial;
	margin: 1em auto;
	width: 75%;
}

header > p:last-of-type{
	font-variant: small-caps;
	margin: 1em;
	text-align: center;
}
```

- [x] I recommend adding the following CSS:
```
section#scene-4-1 p:nth-of-type(2){
	margin: 2em;
}
```
The note in the middle of scene-4-1 was hidden among the dialogue. Since it is such an important note, I think a little more space around it would help differentiate from the rest of the text.

**Colophon:**

- [x] The semantic for the work should be `<i epub:type="se:name.publication.play">`.

**Lint:**

- [x] After making the above changes lint will want you to remove the `div[epub|type~="z3998:scene"] > p` selector.

**Comment by EmmaSweeney** [comment]
**local.css:**
- [x] Scene descriptions and high-level stage directions should both be left-aligned. Just use:
```
p[epub|type~="z3998:stage-direction"]{
	text-indent: 0;
}
```

- [x] Hmm... the margin looks good for the variation note, but now it isn't aligning with the other scene descriptions. I think this additional styling will get it to behave properly.
```
#scene-4-1 p:nth-of-type(2){
	margin: 2em auto;
	text-indent: 0;
}
```

**Comment by weijia-cheng** [comment]
Ok, I've put in the CSS you suggested.
